version: "3"
services:
  open-id-connect-api:
    environment:
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_URL=...
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_CLIENT_ID=...
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_CLIENT_SECRET=...
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_REDIRECT_URI=http://%host%:9501/callback
      - FLUX_OPEN_ID_CONNECT_API_ROUTE_AFTER_LOGIN_URL=/userinfos
      - FLUX_OPEN_ID_CONNECT_API_SESSION_CRYPT_PLAIN=true
      - FLUX_OPEN_ID_CONNECT_API_COOKIE_SECURE=false
    image: docker-registry.fluxpublisher.ch/flux-open-id-connect/api:latest
    ports:
      - [%host_ip%:]9501:9501
  other-service:
    depends_on:
      - open-id-connect-api
    environment:
      [- FLUX_OPEN_ID_CONNECT_API_HOST=open-id-connect-api]
      [- FLUX_OPEN_ID_CONNECT_API_PORT=9501]
